# Generated by Django 5.0.3 on 2025-04-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
