# Generated by Django 5.0.3 on 2025-04-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='buy',
            field=models.BooleanField(default=False),
        ),
    ]
