# Generated by Django 5.0.3 on 2025-04-11 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petowner_profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='petowner_profile',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='petowner_profile',
            name='species',
        ),
    ]
