# Generated by Django 5.0.3 on 2025-04-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_doctor_appointment_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_appointment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
