# Generated by Django 5.0.3 on 2025-04-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_doctor_appointment_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_appointment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
