# Generated by Django 5.0.3 on 2025-04-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_doctor_appointment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='adopt',
            field=models.BooleanField(default=False),
        ),
    ]
