# Generated by Django 5.0.3 on 2025-04-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_adopter'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopter',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
