# Generated by Django 5.0.3 on 2025-04-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctor_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_profile',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
